spring:
  application:
    name: 09-security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys_demo?characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 1
  session:
    store-type: redis
    timeout: 1800000 #半小时过期
server:
  port: 8029
mybatis:
  mapper-locations: classpath:mappers/**/*.xml