spring:
  application:
    name: 08-security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys_demo?characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8008
mybatis:
  mapper-locations: classpath:mappers/**/*.xml