spring:
  application:
    name: 31-security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys_demo?characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 4
server:
  port: 8031
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8030/eureka/

