spring:
  application:
    name: 30-eureka
server:
  port: 8030
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/