spring:
  application:
    name: 23-security
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys_demo?characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.159.130
    port: 6379
    database: 1
    password: 151506
server:
  port: 8023
mybatis:
  mapper-locations: classpath:mappers/**/*.xml